### ISSUE TITLE
Request IT Infrastructure from Global - Dev environment

### ISSUE THREAD

**Issue by cdawson-stantec** [stanlytics/ramm-reporting#12]
---
name: Request IT Infrastructure from Global
about: Request - and get - infrastructure

---

### User Story

As a stantec developer
I want IT infrastructure approved and set up by global for Sandbox environment
So that I can develop the RAMM reporting dashboard in the stantec environment

#### Acceptance Criteria
- [x] confirm where we are supposed to develop application - sandbox environment
- [x] Discuss with Bill the best way to achieve our outcomes @magewire 
- [x] IT Request form (high level) @petehilljnr @magewire 
- [x] IT deliver infrastructure 
- [x] Access and permissions granted to PTL and dev team

Note: 
Discuss sharing within environments, and security. Virtual network required?

[Request for Cloud Technology Solution - RAMM project - based on template v0.1 - v2.docx](https://github.com/stanlytics/ramm-reporting/files/4578021/Request.for.Cloud.Technology.Solution.-.RAMM.project.-.based.on.template.v0.1.-.v2.docx)

**Comment by cdawson-stantec** [comment]
IT infrastructure requested by LB for Prod and Dev Environments.
AL has access to existing (dev/prod) env. 
New Resource is RDMS only.
We need to get a ITMS request form for a sandbox environment

**Comment by magewire** [comment]
Notes from Discussions with Bill:
- IT are still in internal discussions around how best to structure Azure Environments
- He recommends a staging (pre-Deployment) environment in addition to development and deployment
- IT are required to monitor all traffic in and out which may be problematic for SaaS solutions

**Comment by cdawson-stantec** [comment]
@magewire to give an update later in the week when we hear back from IT
Steve McG contacting Global Digital Solutions team  to support us. 
Could be value working with them more closely in future.
Waiting for documentation to proceed.
*Workaround for now - set up in RShiny environment @magewire COB Tues

**Comment by cdawson-stantec** [comment]
Altering request with Global Digital Solutions from Dev environment to Prod envmt

**Comment by cdawson-stantec** [comment]
@magewire to send RTS form to IT 
@Ponting7 chasing firewall ticket with IT

**Comment by Ponting7** [comment]
IT have approved the SMTP Server link form FME server and it should be up and running with in the next 48 hours.

**Comment by cdawson-stantec** [comment]
Sandbox environment available for development
